{% set name = "p4p" %}
{% set version = "3.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdavidsaver/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 42af03661f8c97a58efc410f3d26273a8d162e12c6acc22ba68066c9f814d7c2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - epicscorelibs =7.0.6.99
    - numpy
    - pip
    - ply
    - setuptools
    - setuptools_dso
  run:
    - python
    - cython
    - epicscorelibs =7.0.6.99
    - nose >=1.1.2
    - {{ pin_compatible('numpy') }}
    - ply

test:
  imports:
    - p4p

about:
  home: http://github.com/mdavidsaver/p4p
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for the PVAccess network client and server.
  doc_url: https://mdavidsaver.github.io/p4p/
  dev_url: https://github.com/mdavidsaver/p4p

extra:
  recipe-maintainers:
    - hhslepicka
