{% set name = "p4p" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0786e48302666f44fad71dca783b7ef2aa2373cfe4dbd3115eac655f30fecb33

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - lcls-ii::pvxslibs
  host:
    - python
    - cython
    - epicscorelibs {{ epicscorelibs }}
    - numpy
    - pip
    - ply
    - setuptools
    - setuptools_dso
  run:
    - python
    - cython
    - epicscorelibs {{ epicscorelibs }}
    - nose >=1.1.2
    - {{ pin_compatible('numpy') }}
    - ply

test:
  imports:
    - p4p

about:
  home: https://github.com/epics-base/p4p
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for the PVAccess network client and server.
  doc_url: https://epics-base.github.io/p4p/
  dev_url: https://github.com/epics-base/p4p

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
    - klauer
