{% set name = "p4p" %}
{% set version = "4.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/epics-base/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2b89d7605ae35dc7edad2a36cf6b1d395170698b6d7fdfc3811a8d3ed5183bab
  patches:
    - patch/fix_sys_libs.patch

build:
  skip: True  # [win]
  number: 1
  entry_points:
    - pvagw = p4p.gw:main

requirements:
  build:
    - make
    - perl
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - cython
    - numpy
    - ply
    - pvxs
  run:
    - python
    - numpy
    - ply
    - pvxs

test:
  requires:
    - nose2
  imports:
    - p4p
    - p4p.client.thread
    - p4p.server
  commands:
    - pvagw --help
    - python -m p4p.client.cli -h
    - python -m nose2 p4p

about:
  home: https://github.com/epics-base/p4p
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for the PVAccess network client and server.
  doc_url: https://epics-base.github.io/p4p/
  dev_url: https://github.com/epics-base/p4p

extra:
  recipe-maintainers:
    - simon-ess
    - valmar
    - chrisvam
    - klauer
